name: Print PR data

on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    print-details:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Print Hello World and PR data
              run: |
                  echo "Hello World"
                  echo "PR Title: ${{ github.event.pull_request.title }}"
                  echo "PR Body: ${{ github.event.pull_request.body }}"
                  echo "PR Author: ${{ github.event.pull_request.user.login }}"
                  echo "PR Number: ${{ github.event.pull_request.number }}"
                  echo "PR URL: ${{ github.event.pull_request.html_url }}"
                  echo "Default Branch: ${{ github.event.repository.default_branch }}"
                  echo "Last Commit Message: "
                  echo "$(git log --format=%B -n 1)"
                  echo "Changes Made: "
                  echo "$(git diff ${{ github.event.before }} ${{ github.event.pull_request.head.sha }})"
